/*
 * YoutubeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeAPI.Standard.Http.Client;

using YoutubeAPI.Standard.Models;
using YoutubeAPI.Standard;
using YoutubeAPI.Standard.Utilities;


namespace YoutubeAPI.Standard.Exceptions
{
    public class ExceptionAPIException : APIException 
    {
        // These fields hold the values for the public properties.
        private Models.Error error;

        /// <summary>
        /// Error here!
        /// </summary>
        [JsonProperty("error")]
        public Models.Error Error 
        { 
            get 
            {
                return this.error; 
            } 
            private set 
            {
                this.error = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public ExceptionAPIException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 