/*
 * YoutubeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using YoutubeAPI.Standard;
using YoutubeAPI.Standard.Utilities;
using YoutubeAPI.Standard.Http.Request;
using YoutubeAPI.Standard.Http.Response;
using YoutubeAPI.Standard.Http.Client;
using YoutubeAPI.Standard.Exceptions;

namespace YoutubeAPI.Standard.Controllers
{
    public partial class YoutubeController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static YoutubeController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static YoutubeController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new YoutubeController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// This Endpoint is used to search youtube videos on the basis of given string input.
        /// </summary>
        /// <param name="q">Required parameter: Parameter for search text</param>
        /// <return>Returns the Models.YoutubeResults response from the API call</return>
        public Models.YoutubeResults Search(string q)
        {
            Task<Models.YoutubeResults> t = SearchAsync(q);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// This Endpoint is used to search youtube videos on the basis of given string input.
        /// </summary>
        /// <param name="q">Required parameter: Parameter for search text</param>
        /// <return>Returns the Models.YoutubeResults response from the API call</return>
        public async Task<Models.YoutubeResults> SearchAsync(string q)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/search");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "q", q },
                { "key", Configuration.Key }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<Models.YoutubeResults>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

        /// <summary>
        /// this has been created to do challenge 5.
        /// </summary>
        /// <return>Returns the void response from the API call</return>
        public void Challenge5()
        {
            Task t = Challenge5Async();
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// this has been created to do challenge 5.
        /// </summary>
        /// <return>Returns the void response from the API call</return>
        public async Task Challenge5Async()
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/challenge5");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "key", Configuration.Key }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);
            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

    }
} 