/*
 * YoutubeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeAPI.Standard;
using YoutubeAPI.Standard.Utilities;


namespace YoutubeAPI.Standard.Models
{
    public class Error : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int code;
        private string message;
        private List<Models.ErrorDetail> errors;
        private string status;

        /// <summary>
        /// Error code
        /// </summary>
        [JsonProperty("code")]
        public int Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }

        /// <summary>
        /// Error message
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// Detail error
        /// </summary>
        [JsonProperty("errors")]
        public List<Models.ErrorDetail> Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// Status of request
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }
    }
} 