/*
 * YoutubeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeAPI.Standard;
using YoutubeAPI.Standard.Utilities;


namespace YoutubeAPI.Standard.Models
{
    public class ErrorDetail : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string message;
        private string domain;
        private string reason;

        /// <summary>
        /// Error message
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// Error domain
        /// </summary>
        [JsonProperty("domain")]
        public string Domain 
        { 
            get 
            {
                return this.domain; 
            } 
            set 
            {
                this.domain = value;
                onPropertyChanged("Domain");
            }
        }

        /// <summary>
        /// Error reason
        /// </summary>
        [JsonProperty("reason")]
        public string Reason 
        { 
            get 
            {
                return this.reason; 
            } 
            set 
            {
                this.reason = value;
                onPropertyChanged("Reason");
            }
        }
    }
} 