/*
 * YoutubeAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using YoutubeAPI.Standard;
using YoutubeAPI.Standard.Utilities;


namespace YoutubeAPI.Standard.Models
{
    public class Item : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string kind;
        private string etag;
        private Models.Id id;

        /// <summary>
        /// Kind of search result.
        /// </summary>
        [JsonProperty("kind")]
        public string Kind 
        { 
            get 
            {
                return this.kind; 
            } 
            set 
            {
                this.kind = value;
                onPropertyChanged("Kind");
            }
        }

        /// <summary>
        /// etag
        /// </summary>
        [JsonProperty("etag")]
        public string Etag 
        { 
            get 
            {
                return this.etag; 
            } 
            set 
            {
                this.etag = value;
                onPropertyChanged("Etag");
            }
        }

        /// <summary>
        /// Search result detail.
        /// </summary>
        [JsonProperty("id")]
        public Models.Id Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }
    }
} 